### Headquarter Locations

To make up for the lack of quantitative data that exists for the media, entertainment, arts, and technology pillar, we seeked our news articles to apply text analytics and Natural Language Processing to quantify our data. Black BRAND’s 150 Year Plan recalls that under this pillar, there is a significant gap in the ownership, representation, and narrative/story/portrayal of media. By finding representation in media that revolves around entertainment, arts, and technology, we can bridge the gap using our collection of news articles across the region to portray a story using the positive or negative sentiment in these texts.

The Hampton Roads Region has major news channels with online articles along with several more regional online newspapers. The larger news channels based out of Norfolk do cover a lot more articles related to our pillar of entertainment, media, arts, and technology with more manpower, whereas some publications talked about more lifestyle content. It should be noted that some of the newspapers did cover numerous regions with its headquarters in one place and smaller regions of Hampton Roads shared publications, with its headquarters in the bigger city. For example, Smithfield Times based in Smithfield covered the Isle of Wight and Surry Counties. Tidewater News covers the areas of Franklin, Southampton County, and Isle of Wight County but has its headquarters based in Franklin. The Gazette Journal based in Gloucester also covers Mathews. To cover articles than span across multiple regions of Hampton Roads, we did have to go past a paywall to obtain more diverse data. Any articles with its headquarters outside of the Hampton Roads area were from Virginia news websites that happened to write about the region still. While we tried to find an equal amount of sources per region, it was still difficult when some publications lacked in articles about entertainment, media, technology, or arts.