With the large sum of articles revolving around the media pillar representing the Hampton Roads region, we finally had enough text to be parsed by our algorithm to fall under the word bank categories of positive, negative, and diversity. Our algorithm not only can parse single words from the articles’ texts, but also phrases that fall under our diversity word bank. This interactive visualization aims to see how the sentiment of positive and negative and its ratio changes over the years as our data has articles from as early as 2010. It is important to notice this progress over the years to see if the work that has been done for the region is effective or if a narrative was being created that conveyed there are still some work to be done. While there was a large spike of diversity in one year that dropped, it still stayed relatively stagnant. The negative sentiment in the articles decreased over the years while positive sentiment increases even as diversity remains. It appears that with the existing articles revolving around this pillars shows that media of the region is relatively positive.

# ### Limitations

Note to viewers and anyone who references this information, we have web scraped the diversity, positive, and negative word banks from online. We attempted as much as we could to well as containing our word bank to focus on racial and ethnic diversity. While diversity is intersectional, we believe that focusing on racial and ethnic diversity aligns best with Black BRAND’s 150 Year Plan. To prevent misleading the audience and keep things as transparent as possible, we have added our word banks under the “Data and Methodology” tab under “Overview.” In addition, these article prevent biases are exclusively about media, entertainment, arts, and technology. It is possible that we could have recorded sentiment of overall media in the region but would have been difficult with the given timeframe.